/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainHomeRouteImport } from './routes/_main/home'
import { Route as MainHistoryRouteImport } from './routes/_main/history'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainResearchIndexRouteImport } from './routes/_main/research.index'
import { Route as MainResearchResearchIdRouteImport } from './routes/_main/research.$researchId'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)
const MainHistoryRoute = MainHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainResearchIndexRoute = MainResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => MainRoute,
} as any)
const MainResearchResearchIdRoute = MainResearchResearchIdRouteImport.update({
  id: '/research/$researchId',
  path: '/research/$researchId',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/history': typeof MainHistoryRoute
  '/home': typeof MainHomeRoute
  '/research/$researchId': typeof MainResearchResearchIdRoute
  '/research': typeof MainResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/history': typeof MainHistoryRoute
  '/home': typeof MainHomeRoute
  '/research/$researchId': typeof MainResearchResearchIdRoute
  '/research': typeof MainResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/history': typeof MainHistoryRoute
  '/_main/home': typeof MainHomeRoute
  '/_main/research/$researchId': typeof MainResearchResearchIdRoute
  '/_main/research/': typeof MainResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/history'
    | '/home'
    | '/research/$researchId'
    | '/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/history'
    | '/home'
    | '/research/$researchId'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/history'
    | '/_main/home'
    | '/_main/research/$researchId'
    | '/_main/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/history': {
      id: '/_main/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof MainHistoryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/research/': {
      id: '/_main/research/'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof MainResearchIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/research/$researchId': {
      id: '/_main/research/$researchId'
      path: '/research/$researchId'
      fullPath: '/research/$researchId'
      preLoaderRoute: typeof MainResearchResearchIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainHistoryRoute: typeof MainHistoryRoute
  MainHomeRoute: typeof MainHomeRoute
  MainResearchResearchIdRoute: typeof MainResearchResearchIdRoute
  MainResearchIndexRoute: typeof MainResearchIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHistoryRoute: MainHistoryRoute,
  MainHomeRoute: MainHomeRoute,
  MainResearchResearchIdRoute: MainResearchResearchIdRoute,
  MainResearchIndexRoute: MainResearchIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
